FROM eclipse-temurin:21-jdk

WORKDIR /app

COPY Backend/demo/mvnw .
COPY Backend/demo/.mvn .mvn
COPY Backend/demo/pom.xml .
COPY Backend/demo/src src

RUN chmod +x mvnw

EXPOSE 8080

CMD ["./mvnw", "spring-boot:run"]